config/routes.rb
Buff::Application.routes.draw do
  resources :pins

  devise_for :users
  get "home" => 'pins#index'
  root 'pins#index'
  get 'paleo' => 'pins#paleoindex'
  get 'cats' => 'pins#catsindex'
  get 'code' => 'pins#codeindex'
  get 'stuff' => 'pins#stuffindex'

  

  

end

app/models/pin.rb
class Pin < ActiveRecord::Base
  attr_accessible :description, :image, :pin_type # This line won't work in Rails 4, instead, you'll have to do what I show below

  validates :description, presence: true
  validates :user_id, presence: true
  has_attached_file :image, styles: { medium: "320x240>"}
  validates_attachment :image, presence: true,
                            content_type: { content_type: ['image/jpeg', 'image/jpg', 'image/png', 'image/gif'] },
                            size: { less_than: 5.megabytes }

  validates_inclusion_of :pin_type, in: Choices['pin_type']
  belongs_to :user
  has_attached_file :image, styles: { medium: "320x240"}

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :name
  # attr_accessible :title, :body
  has_many :pins
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def cats
  end

  def paleo
  end

  def stuff
  end

  def code
  end

end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_filter :authenticate_user!, except: [:index]
  before_action :set_pin, only: [:show, :edit, :update, :destroy]

  # GET /pins
  # GET /pins.json
  def index
    @pins = Pin.order("created_at desc")
  end

  def catsindex
    @pins = Pin.order("created_at desc").find(:all, :conditions => {:pin_type => 'cats'})
    render 'index'
  end

  def paleoindex
    @pins = Pin.order("created_at desc").find(:all, :conditions => {:pin_type => 'paleo'})
    render 'index'
  end

  def codeindex
    @pins = Pin.order("created_at desc").find(:all, :conditions => {:pin_type => 'code'})
    render 'index'
  end

  def stuffindex
    @pins = Pin.order("created_at desc").find(:all, :conditions => {:pin_type => 'stuff'})
    render 'index'
  end

  # GET /pins/1
  # GET /pins/1.json
  def show
  end

  # GET /pins/new
  def new
    @pin = current_user.pins.new
  end

  # GET /pins/1/edit
  def edit
    @pin = current_user.pins.find(params[:id])
  end

  # POST /pins
  # POST /pins.json
  def create
    @pin = current_user.pins.new(params[:pin])

    respond_to do |format|
      if @pin.save
        format.html { redirect_to @pin, notice: 'Pin was successfully created.' }
        format.json { render action: 'show', status: :created, location: @pin }
      else
        format.html { render action: 'new' }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pins/1
  # PATCH/PUT /pins/1.json
  def update
    @pin = current_user.pins.find(params[:id])
    respond_to do |format|
      if @pin.update_attributes(params[:pin])
        format.html { redirect_to @pin, notice: 'Pin was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pins/1
  # DELETE /pins/1.json
  def destroy
    @pin = current_user.pins.find(params[:id])
    @pin.destroy
    respond_to do |format|
      format.html { redirect_to pins_url }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_pin
    @pin = Pin.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def pin_params
    params.require(:pin).permit(:description)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/layouts/_footer.html.erb
<div class="footer">
    <small>
        <%= link_to "awkwardtechlady.com", "www.awkwardtechlady.com" %>
        by <%= link_to "Kelley", "http://www.linkedin.com/in/kelleydowney/" %>
    </small>
</div>

app/views/layouts/_header.html.erb
<div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
        <div class="container">
            <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </a>
             <a class="brand" href="/">ATL</a>

                <div class="nav-collapse">
                    <ul class="nav">
                        <li>
                            <%= link_to 'Cats',  cats_path %>
                        </li>
                        <li>    
                            <%= link_to 'Paleo',  paleo_path %>
                        </li>
                           <li>
                            <%= link_to 'Code',  code_path %>
                        </li>
                        <li>    
                            <%= link_to 'Stuff',  stuff_path %>
                        </li>
                    </ul>
                    <ul class="nav pull-right">
                                <% if user_signed_in? %>
                                    <li><%= link_to "Add Post", new_pin_path %></li>
                                    <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
                                    <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
                                <% else %>
                                <li><%= link_to 'Login',  new_user_session_path %></li>
                                
                                <% end %>
                                
                    </ul>
                </div>
        </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Buff</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
	<%= render 'layouts/header' %>
	<% flash.each do |name, msg| %>
       <%= content_tag(:div, msg, class: "alert alert-#{name}") %>
       <% end %>
    <%= yield %>
    <%= render 'layouts/footer' %>
</div>

</body>
</html>

app/views/pages/_home.html.erb
<div>
	<!--  Carousel - consult the Twitter Bootstrap docs at
      http://twitter.github.com/bootstrap/javascript.html#carousel -->
<div id="this-carousel-id" class="carousel slide"><!-- class of slide for animation -->
  <div class="carousel-inner">
    <div class="item active"><!-- class of active since it's the first item -->
      <img src="/logo.png" alt="" />
      <div class="carousel-caption">
        <p>Welcome to my blog!</p>
      </div>
    </div>
    <div class="item">
      <img src="/buffdrawer1200x480.jpg" alt="" />
      <div class="carousel-caption">
        
      </div>
    </div>
    <div class="item">
      <img src="/programminglanguages.jpg" alt="" />
      <div class="carousel-caption">
        <p>www.coursera.org/course/proglang</p>
      </div>
    </div>
    <div class="item">
      <img src="/paleo.jpg" alt="" />
      <div class="carousel-caption">
        <p>90 Days of Paleo and Crossfit</p>
      </div>
    </div>
  </div><!-- /.carousel-inner -->
  <!--  Next and Previous controls below
        href values must reference the id for this carousel -->
    <a class="carousel-control left" href="#this-carousel-id" data-slide="prev">&lsaquo;</a>
    <a class="carousel-control right" href="#this-carousel-id" data-slide="next">&rsaquo;</a>
</div><!-- /.carousel -->

    <!-- <p> <%= link_to 'Sign up',  new_user_registration_path , class: "btn btn-large btn-primary" %> </p> -->
</div>

app/views/pages/about.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

<%= link_to "Home", home_path %>

app/views/pages/cats.html.erb
cat

app/views/pages/code.html.erb
code

app/views/pages/paleo.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

<%= link_to "Home", home_path %>


paleo

app/views/pages/stuff.html.erb
stuff

app/views/pins/_form.html.erb
<%= simple_form_for(@pin, html: { class: "form-horizontal"}) do |f| %>
  <%= f.error_notification %>
  <%= f.full_error :image_file_size, class: "alert alert-error" %>
  <%= f.full_error :image_content_type, class: "alert alert-error" %>

  <%= f.input :image, label: "Upload an image" %>
  <%= f.input :description, as: :text, input_html: { rows: "3" } %>
  <%= f.input :pin_type, :collection => Choices['pin_type'] %>

  <div class="form-actions">
    <%= f.button :submit, class: "btn btn-primary" %>
  </div>
<% end %>

app/views/pins/_pin.html.erb
<div class="box">
    <%= link_to (image_tag pin.image(:medium)), pin %>
    <p class="description">
        <%= pin.description %>
    </p>
    <p>
        <strong>
            Posted by <%= pin.user.name %>
        </strong>
    </p>
    <% if current_user == pin.user %>
        <p>
          <%= link_to 'Edit', edit_pin_path(pin) %>
        </p>
        <p>
          <%= link_to 'Delete', pin, method: :delete, data: { confirm: 'Are you sure you want to delete this pin?' } %>
        </p>
    <% end %>
</div>

app/views/pins/edit.html.erb
<h1>Editing pin</h1>

<%= render 'form' %>

<%= link_to 'Show', @pin %> |
<%= link_to 'Back', pins_path %>

app/views/pins/index.html.erb
<%= render 'pages/home' %>

<div id="pins">
  <%= render @pins %>
</div>

app/views/pins/new.html.erb
<%= render 'form' %>

<%= link_to 'Back', pins_path %>

app/views/pins/show.html.erb
<div class="row">
    <div class="span6 offset3">
        <div class="well">
            <%= image_tag @pin.image %>
            <p>
              <%= @pin.description %>
            </p>
            <p>
              <%= @pin.user.name %>
            </p>
            <% if current_user == @pin.user %>
                <%= link_to 'Edit', edit_pin_path(@pin) %> |
            <% end %>
            <%= link_to 'Back', pins_path %>
        </div>
    </div>
</div>